linters:

  BorderZero:
    enabled: true
    convention: zero
    severity: error

  BemDepth:
    enabled: true
    severity: warning

  Comment:
    enabled: true
    severity: error
    allowed: '^\/\*\*$'

  Indentation:
    enabled: true
    severity: error
    width: 2

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: single_quotes